server:
  port: 8081
  servlet:
    context-path: /parking-space-service

spring:
  application:
    name: parking-space-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/