spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**

        - id: parking-space-service
          uri: http://localhost:8081
          predicates:
            - Path=/parking-space-service/**

        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payment-service/**

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/user-service/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/