server:
  port: 8082
  servlet:
    context-path: /config-service

spring:
  application:
    name: config-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


