spring:
  application:
    name: config-service
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      server:
        native:
          search-locations: config-service/src/main/resources/config
  profiles:
    active: native

server:
  port: 8889




